### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ghost** [ngscheurich/generator-phaser-ts#12]
I have been trying to install this generator with both yarn and npm but it fails on both and as it appears it cannot find package.json file:

```
yarn global v0.17.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Couldn't find a package.json file in "/Users/iulian/Library/Caches/Yarn/npm-generator-phaser-ts-0.2.4-d4f7534ca044b13c7990e2abf3b5f33ebc857424"
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

```
/usr/local/lib
└── (empty)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-phaser-ts"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! path /usr/local/lib/node_modules/.staging/generator-phaser-ts-2604978a/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/generator-phaser-ts-2604978a/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/.staging/generator-phaser-ts-2604978a/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iulian/npm-debug.log
npm ERR! code 1
```

**Comment by ngscheurich** [comment]
Hi, @iulianvrz. Thanks for sharing your issue! I was able to replicate the problem, and my hypothesis is that something went wrong when I published to the npm registry via Yarn.

I've made some improvements to the code (as well as removed the Yarn dependency) and published the latest version via npm, and everything seems to work okay now.

I'll leave the issue open until I hear back from you in case you have further issues.

I confirmed the issue as well as the fix on a fresh Ubuntu install, which I'll detail below.

---

Assuming you have [Vagrant](https://www.vagrantup.com/) installed:

```shell
$ vagrant box add hashicorp/precise64
$ vagrant init hashicorp/precise64
$ vagrant up
```

After `vagrant ssh`-ing:
```shell
$ sudo apt-get install -y curl
$ curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
$ sudo apt-get update
$ sudo apt-get install -y nodejs git
$ sudo npm install -g yo generator-phaser-ts
$ yo phaser-ts
```

**Comment by ghost** [comment]
Hey @ngscheurich. Yeah, now it works. I tested on the same machine and it installs without any issue. 

I encountered a issue/bug into the generator itself. For the first 2 booleans the answers are (Y/n) and for the last one (Heroku) is (y/N) and if you enter (n) it crashes with the following message:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at namespace.props.projectName.replace.split.map (/usr/local/lib/node_modules/generator-phaser-ts/generators/app/index.js:101:27)
    at Array.map (native)
    at child.writing (/usr/local/lib/node_modules/generator-phaser-ts/generators/app/index.js:101:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-phaser-ts/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-phaser-ts/node_modules/run-async/index.js:25:25
    at /usr/local/lib/node_modules/generator-phaser-ts/node_modules/run-async/index.js:24:19
    at /usr/local/lib/node_modules/generator-phaser-ts/node_modules/yeoman-generator/lib/base.js:432:9
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by ngscheurich** [comment]
Hmm… I'm not able to replicate that one in the same fashion. From the looks of the error message it seems like perhaps you didn't enter a game name in response the first question (*So what’s your game called?*); or maybe the generator didn't pick up your input. Do you recall if you entered anything?

I've been meaning to have the generator use the directory name by default (https://github.com/ngscheurich/generator-phaser-ts/issues/9), but for now it requires some sort of input.

Let me know!

**Comment by ghost** [comment]
@ngscheurich for the heroku question I entered (n) not (N) and then it throwed that error, I am saying this because the first two boolean questions where (Y/n) and the last one for heroku it was (y/N) . 

Edit: I am reffering to [this](https://github.com/ngscheurich/generator-phaser-ts/blob/master/generators/app/index.js#L42) 

```
 {
      type    : 'confirm',
      name    : 'installDeps',
      message : 'Shall I install your dependencies?',
      default : true
    }, {
      type    : 'confirm',
      name    : 'git',
      message : 'Might I initialize a Git repository for you?',
      default : true
    }, {
      type    : 'confirm',
      name    : 'heroku',
      message : 'Would you care for a Heroku app?',
      default : false
    }
```

**Comment by ngscheurich** [comment]
@iulianvrz Yeah, I didn't want Heroku configured all the time, so its default is *N* whereas for me it makes sense for the previous two to default to *Y*. That being said, I tested answering the Heroku question with *n* and it worked okay on my end. The only way I am able to get the error you posted was by not entering anything in response to the first question.

Here's a quick screencast in case I'm doing a poor job explaining:

[![asciicast](https://asciinema.org/a/3pfy2e5godftj0otu1vdk32hk.png)](https://asciinema.org/a/3pfy2e5godftj0otu1vdk32hk)

**Comment by ghost** [comment]
@ngscheurich Yup I have exactly the same issue, so it's related to not entering any name in project name.

**Comment by ngscheurich** [comment]
@iulianvrz 🍻 Cool. I'll close this issue and get around to implementing some sort of default game name… probably.
