### ISSUE TITLE
gulp watch not working for me

### ISSUE THREAD

**Issue by smatthews1999** [ngscheurich/generator-phaser-ts#13]
Hi.  

I was wondering if you could tell me how to run this without node, and to instead use an index.html file.

Thanks.

**Comment by ngscheurich** [comment]
Hey, @smatthews1999! Sorry it took so long to get back to you. If you're still having this issue I'd be glad to help. Send me some info about your environment (OS and Node version, specifically) if I can still help you, otherwise let me know you're good and I'll close this issue.

Cheers.

**Comment by ngscheurich** [comment]
My bad, @smatthews1999—I didn't understand the initial question fully.

So, you're going to need Node to handle all of the TypeScript transpilation, JavaScript concatenation, etc. (basically, all the stuff that Gulp is handling).

*However*, once all of that work has been performed, you should be able to simply create a static HTML page and link up the assets from the `public` directory in your markup—something like:

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Phaser TS HTML page</title>
    <link href="public/css/main.css" rel="stylesheet">
    <script src="public/js/bundle.js"></script>
  </head>
  <body>
  </body>
</html>
```

You may have to tweak some file paths depending on how you're serving the HTML, but that's the gist of it.

Does that help?

**Comment by ngscheurich** [comment]
Also, note: The instructions currently say to run `npm server` but should actually say to run `npm run server`. I'll fix that in a bit; just wanted to make sure that wasn't part of the problem.
